-- CreateEnum
CREATE TYPE "MedicalFormStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'REVIEWED', 'APPROVED');

-- CreateTable
CREATE TABLE "medical_forms" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "child_name" TEXT NOT NULL,
    "child_birth_date" TIMESTAMP(3) NOT NULL,
    "child_age_years" TEXT,
    "child_age_months" TEXT,
    "pregnancy_type" TEXT,
    "premature_weeks" TEXT,
    "post_term_weeks" TEXT,
    "pregnancy_complications" TEXT,
    "delivery_type" TEXT,
    "cesarean_reason" TEXT,
    "birth_weight" TEXT,
    "birth_height" TEXT,
    "delivery_complications" TEXT,
    "complication_details" TEXT,
    "special_care" TEXT[],
    "hospitalization_days" TEXT,
    "hospitalization_reason" TEXT,
    "important_illnesses" TEXT[],
    "other_illness" TEXT,
    "hospitalizations" JSONB NOT NULL,
    "previous_surgeries" TEXT,
    "surgery_details" TEXT,
    "surgery_age" TEXT,
    "takes_medications" TEXT,
    "medications" JSONB NOT NULL,
    "food_allergies" TEXT[],
    "other_food_allergy" TEXT,
    "medication_allergies" TEXT[],
    "other_medication_allergy" TEXT,
    "other_allergies" TEXT[],
    "other_allergy_description" TEXT,
    "head_control_age" TEXT,
    "sitting_age" TEXT,
    "crawling_age" TEXT,
    "walking_age" TEXT,
    "climbs_stairs" BOOLEAN NOT NULL DEFAULT false,
    "balance_difficulties" TEXT,
    "balance_difficulty_details" TEXT,
    "fine_motor_skills" TEXT[],
    "block_towers" TEXT,
    "fine_motor_difficulties" TEXT,
    "fine_motor_difficulty_details" TEXT,
    "first_words_age" TEXT,
    "two_word_phrases_age" TEXT,
    "complete_sentences" BOOLEAN NOT NULL DEFAULT false,
    "current_communication" TEXT[],
    "other_communication" TEXT,
    "comprehension" TEXT,
    "follows_simple_instructions" BOOLEAN NOT NULL DEFAULT false,
    "follows_complex_instructions" BOOLEAN NOT NULL DEFAULT false,
    "responds_to_name" BOOLEAN NOT NULL DEFAULT false,
    "cognitive_development" TEXT[],
    "learning_difficulties" TEXT,
    "interacts_with_children" TEXT,
    "interaction_details" TEXT,
    "shares_toys" BOOLEAN NOT NULL DEFAULT false,
    "expresses_emotions" BOOLEAN NOT NULL DEFAULT false,
    "tantrums" TEXT,
    "tantrum_frequency" TEXT,
    "adapts_to_changes" TEXT,
    "repetitive_behaviors" TEXT,
    "behavior_details" TEXT,
    "feeding_habits" TEXT[],
    "uses_utensils" BOOLEAN NOT NULL DEFAULT false,
    "sleep_habits" TEXT[],
    "daytime_toilet_control" TEXT,
    "nighttime_toilet_control" TEXT,
    "uses_diapers" BOOLEAN NOT NULL DEFAULT false,
    "diaper_age" TEXT,
    "lives_with_whom" TEXT,
    "has_siblings" TEXT,
    "number_of_siblings" TEXT,
    "siblings_ages" TEXT,
    "family_environment" TEXT,
    "recent_changes" TEXT,
    "types_of_changes" TEXT[],
    "other_change" TEXT,
    "change_details" TEXT,
    "family_history" TEXT,
    "family_history_details" TEXT,
    "status" "MedicalFormStatus" NOT NULL DEFAULT 'DRAFT',
    "submitted_at" TIMESTAMP(3),
    "reviewed_at" TIMESTAMP(3),
    "reviewed_by" TEXT,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "medical_forms_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "medical_forms_appointment_id_key" ON "medical_forms"("appointment_id");

-- CreateIndex
CREATE INDEX "medical_forms_appointment_id_idx" ON "medical_forms"("appointment_id");

-- AddForeignKey
ALTER TABLE "medical_forms" ADD CONSTRAINT "medical_forms_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
